vim.g.mapleader = " "
vim.g.maplocalleader = " "

require "keymaps"
require "plugins.lazy"
require "plugins.lualine"
require "options"
require "plugins.telescope"
require "plugins.treesitter"
require "plugins.lsp"
require "plugins.trouble"
require "plugins.codesnap"
require "plugins.mini"
require "plugins.conform"
